plugins {
	id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
	mappings channel: 'official', version: project.minecraft_version

	copyIdeResources = true

	runs {
		client {
			workingDirectory project.file('run')

			property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			property 'mixin.env.remapRefMap', 'true'
			property 'mixin.env.refMapRemappingFile', "${project.buildDir}/createSrgToMcp/output.srg"

			mods {
				continuity {
					source sourceSets.main
				}
			}
		}
	}
}

dependencies {
	minecraft "net.minecraftforge:forge:${project.forge_version}"

	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
	inputs.property 'version', project.version

	filesMatching('META-INF/mods.toml') {
		expand 'version': project.version
	}
}

jar {
	from('LICENSE') {
		rename { "${it}_${project.base.archivesName.get()}" }
	}

	manifest {
		attributes([
				"Specification-Title"     : "continuity",
				"Specification-Version"   : "1",
				"Implementation-Title"    : project.name,
				"Implementation-Version"  : project.jar.archiveVersion,
				"MixinConfigs"            : "continuity.mixins.json"
		])
	}
}

// configure the maven publication
publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}
